services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_POLL_INTERVAL=86400

    # If you want to run only once
    restart: always         # Comment this
    #command: --run-once    # Uncomment this

